#include "effect_def.h"

void EffectDef::_bind_methods() {
	BIND_ENUM_CONSTANT(NONE);
	BIND_ENUM_CONSTANT(FLAVOR_TEXT);
	BIND_ENUM_CONSTANT(STAT);
	BIND_ENUM_CONSTANT(EMPOWER);
	BIND_ENUM_CONSTANT(SUMMON);
	BIND_ENUM_CONSTANT(HEAL);
	BIND_ENUM_CONSTANT(TP);
	BIND_ENUM_CONSTANT(NUMB);
	BIND_ENUM_CONSTANT(RAW_STAT);
	BIND_ENUM_CONSTANT(MULTIPLY_HEALING);
	BIND_ENUM_CONSTANT(PREVENT_NUMB);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_ADD);
	BIND_ENUM_CONSTANT(MODIFY_CARD_COST);
	BIND_ENUM_CONSTANT(DRAW_CARD);
	BIND_ENUM_CONSTANT(MODIFY_GAME_RULE);
	BIND_ENUM_CONSTANT(DELAY_SETUP);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REMOVE);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_MOVE);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REPLACE);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_ADD_HAND);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REMOVE_HAND);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_MOVE_HAND);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REPLACE_HAND);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_ADD_DECK);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REMOVE_DECK);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_MOVE_DECK);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REPLACE_DECK);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_ADD_FIELD);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REMOVE_FIELD);
	BIND_ENUM_CONSTANT(MODIFY_AVAILABLE_CARDS_REPLACE_FIELD);
        
	BIND_ENUM_CONSTANT(LEGACY_SET_MUSIC);
	BIND_ENUM_CONSTANT(LEGACY_PLAY_SOUND);
	BIND_ENUM_CONSTANT(SET_STAGE);
	BIND_ENUM_CONSTANT(SET_MUSIC);
	BIND_ENUM_CONSTANT(PLAY_SOUND);
        
	BIND_ENUM_CONSTANT(COND_CARD);
	BIND_ENUM_CONSTANT(COND_LIMIT);
	BIND_ENUM_CONSTANT(COND_WINNER);
	BIND_ENUM_CONSTANT(COND_APPLY);
	BIND_ENUM_CONSTANT(COND_COIN);
	BIND_ENUM_CONSTANT(COND_STAT);
	BIND_ENUM_CONSTANT(COND_IN_HAND);
	BIND_ENUM_CONSTANT(COND_LAST_EFFECT);
	BIND_ENUM_CONSTANT(COND_ON_NUMB);
	BIND_ENUM_CONSTANT(COND_MULTIPLE_EFFECTS);
	BIND_ENUM_CONSTANT(COND_ON_DISCARD);
	BIND_ENUM_CONSTANT(COND_COMPARE_TARGET_CARD);
	BIND_ENUM_CONSTANT(COND_ON_EXILE);
	BIND_ENUM_CONSTANT(COND_TIE);
	BIND_ENUM_CONSTANT(COND_STAT_MATH);
        
	BIND_ENUM_CONSTANT(FIRST_CUSTOM);

	BIND_PROPERTY(Variant::STRING, editor_name);
	BIND_PROPERTY(Variant::INT, default_priority);
	BIND_PROPERTY_RESOURCE_ARRAY(JigsawParameter, default_parameters);
	BIND_PROPERTY(Variant::PACKED_STRING_ARRAY, parameter_names);
	BIND_PROPERTY_RESOURCE_ARRAY(JigsawTrigger, triggers);
	BIND_PROPERTY_RESOURCE(JigsawCommandList, describe);
	BIND_PROPERTY_RESOURCE(JigsawCommandList, simple_describe);
	BIND_PROPERTY_RESOURCE(JigsawCommandList, curve);
}

IMPLEMENT_PROPERTY(EffectDef, String, editor_name);
IMPLEMENT_PROPERTY(EffectDef, int64_t, default_priority);
IMPLEMENT_PROPERTY(EffectDef, TypedArray<JigsawParameter>, default_parameters);
IMPLEMENT_PROPERTY(EffectDef, PackedStringArray, parameter_names);
IMPLEMENT_PROPERTY(EffectDef, TypedArray<JigsawTrigger>, triggers);
IMPLEMENT_PROPERTY(EffectDef, Ref<JigsawCommandList>, describe);
IMPLEMENT_PROPERTY(EffectDef, Ref<JigsawCommandList>, simple_describe);
IMPLEMENT_PROPERTY(EffectDef, Ref<JigsawCommandList>, curve);
