#ifndef ENUMS_VARIABLE_DEF_H
#define ENUMS_VARIABLE_DEF_H

namespace enums {
namespace VariableDef {
enum Variable {
	NONE = -1,

	TARGET_CARD = 0,
	LIMIT_COUNT = 1,

	MAX_HP = 241,
	HAND_MIN_SIZE = 242,
	HAND_MAX_SIZE = 243,
	DRAW_PER_ROUND = 244,
	CARDS_PER_DECK = 245,
	MIN_TP = 246,
	MAX_TP = 247,
	TP_PER_ROUND = 248,
	BOSS_CARDS = 249,
	MINI_BOSS_CARDS = 250,
	DUPLICATE_BOSS = 251,
	DUPLICATE_MINI_BOSS = 252,
	DUPLICATE_EFFECT = 253,
	DUPLICATE_ATTACKER = 254,
	CARDS_PER_ROUND = 255,
	FIRST_LEGACY_GAME_RULE = MAX_HP,

	FIRST_CUSTOM = 256,
};
}
}
DECLARE_ENUM(enums::VariableDef::Variable);

#endif // ENUMS_VARIABLE_DEF_H
