#include "jigsaw_parameter.h"

void JigsawParameter::_bind_methods() {
	BIND_ENUM_CONSTANT(SPRITE_INSTANCE);
	BIND_ENUM_CONSTANT(SCENE_INSTANCE);
	BIND_ENUM_CONSTANT(QUEUED_EFFECT);
	BIND_ENUM_CONSTANT(MODIFIER_INSTANCE);
	BIND_ENUM_CONSTANT(CARD_INSTANCE);
	BIND_ENUM_CONSTANT(FORMATTED_TEXT);
	BIND_ENUM_CONSTANT(ORDERED_LIST);
	BIND_ENUM_CONSTANT(LOCAL_VARIABLE);
	BIND_ENUM_CONSTANT(VARIABLE);
	BIND_ENUM_CONSTANT(BOOLEAN);
	BIND_ENUM_CONSTANT(AMOUNT);
	BIND_ENUM_CONSTANT(FLOAT);
	BIND_ENUM_CONSTANT(STRING);
	BIND_ENUM_CONSTANT(EFFECT_INSTANCE);
	BIND_ENUM_CONSTANT(CARD_FILTER);
	BIND_ENUM_CONSTANT(CARD);
	BIND_ENUM_CONSTANT(STAT);
	BIND_ENUM_CONSTANT(RANK);
	BIND_ENUM_CONSTANT(TRIBE);
	BIND_ENUM_CONSTANT(MODIFIER);
	BIND_ENUM_CONSTANT(LOCATION);
	BIND_ENUM_CONSTANT(ICON);
	BIND_ENUM_CONSTANT(CID_OPUS);
	BIND_ENUM_CONSTANT(FILE_ID_OPUS);
	BIND_ENUM_CONSTANT(FILE_ID_GLTF);
	BIND_ENUM_CONSTANT(COLOR);
	BIND_ENUM_CONSTANT(CHOICE);

	ClassDB::bind_method(D_METHOD("get_type"), &JigsawParameter::get_type);
	ADD_PROPERTY(PropertyInfo(Variant::INT, "type"), "", "get_type");
}
