#include "tribe_def.h"

void TribeDef::_bind_methods() {
	BIND_ENUM_CONSTANT(NONE);

	BIND_ENUM_CONSTANT(SEEDLING);
	BIND_ENUM_CONSTANT(WASP);
	BIND_ENUM_CONSTANT(FUNGI);
	BIND_ENUM_CONSTANT(ZOMBIE);
	BIND_ENUM_CONSTANT(PLANT);
	BIND_ENUM_CONSTANT(BUG);
	BIND_ENUM_CONSTANT(BOT);
	BIND_ENUM_CONSTANT(THUG);
	BIND_ENUM_CONSTANT(UNKNOWN);
	BIND_ENUM_CONSTANT(CHOMPER);
	BIND_ENUM_CONSTANT(LEAFBUG);
	BIND_ENUM_CONSTANT(DEAD_LANDER);
	BIND_ENUM_CONSTANT(MOTHFLY);
	BIND_ENUM_CONSTANT(SPIDER);
	BIND_ENUM_CONSTANT(LEGACY_CUSTOM);
	BIND_ENUM_CONSTANT(LEGACY_NONE);

	BIND_ENUM_CONSTANT(FIRST_CUSTOM);

	BIND_ENUM_CONSTANT(NORMAL);
	BIND_ENUM_CONSTANT(HIDDEN);
	BIND_ENUM_CONSTANT(WIDE);

	BIND_PROPERTY(Variant::STRING, name);
	BIND_PROPERTY(Variant::COLOR, color);
	BIND_PROPERTY(Variant::INT, display);
}

IMPLEMENT_PROPERTY(TribeDef, String, name);
IMPLEMENT_PROPERTY(TribeDef, Color, color);
IMPLEMENT_PROPERTY(TribeDef, TribeDef::DisplayMode, display);
